version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: sh -c "node dist/db/seed.js && node dist/index.js"
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data:
